baseURL = "smartassistant-unicamp.github.io/"
title = "Smart Assistant"
theme = ["ananke"]
resourceDir = "./public"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 20

[params]
site_logo = ""
favicon = "./img/favicon.ico"
github = "https://github.com/smartassistant-unicamp"

[menu]
    [[menu.main]]
    name = "Home"
    url = "/about"
    weight = 1

    [[menu.main]]
    name = "Research"
    url = "/research"
    weight = 2

    [[menu.main]]
    name = "Members"
    url = "/members/"
    weight = 3

    [[menu.main]]
    name = "Awards"
    url = "/awards"
    weight = 4

    [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 5

    [[menu.main]]
    name = "Products"
    url = "/products"
    weight = 6

    [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 7
